FROM node:9.2.0

RUN mkdir -p /data/api
COPY ./api /data/api
ADD ./cms/dist /data/api/public

WORKDIR /data/api/

RUN npm config set registry "http://registry.npm.taobao.org/"
RUN npm install

RUN chmod a+x ./entrypoint.sh

EXPOSE 8080

CMD ./entrypoint.sh pro